### ISSUE TITLE
Expo CLI versus React Native CLI

### ISSUE THREAD

**Issue by jongan69** [Florida-Poly-Prophet/PolyProphetApp#1]
Since the application was initialized using expo, we will be more limited in our development since Expo is more of a sandbox development library build for react native.

The react native cli is slightly more difficult to build in comparison to expo but limits or capability without ejecting the application from using React Native all together.

Please see: https://stackoverflow.com/questions/54862388/what-is-the-difference-between-expo-cli-and-react-native-cli

**Comment by chaotictoejam** [comment]
You are free to make the change on a new branch!
