### ISSUE TITLE
Repository details

### ISSUE THREAD

**Issue by Luckey-Elijah** [Florida-Poly-Prophet/PolyProphetApp#3]
Hello, a committee member reached out to me asking if I would like to help/contribute/join the team. I am very interest and would love to see app architecture, contributing guidelines, and goals in the app.

I am also willing to contribute to these, but would love to see other _interested_ contributors find a way to get started.

Again if you want me to create some guidelines for contributing (a simple `CONTRIBUTING.md`)  and having some body filling out the `README.md` so people have a good place to start for contributing! 

Happy hacking!

**Comment by chaotictoejam** [comment]
Hi Elijah, this repo and organization are for the Poly Prophet teams (Mobile App, Website, and WebApi), and it is the teams that will be updating documentation for this repos. If you are interested in being part of the app development teams please meet with the Team Lead so you can be placed on an appropriate team, also if you chose to join the development please make sure you can make the meetings.
